### ISSUE TITLE
Erro ao acessar artigos sem título

### ISSUE THREAD

**Issue by patymori** [scieloorg/opac#1348]
### Descrição do problema
Ao tentar acessar artigos sem título na versão `master`, ocorre um erro. A alteração feita em 5e27006 que ocasionou o problema. O erro não ocorre na versão da `master-sp`. Segue o traceback do erro:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_caching/__init__.py", line 366, in decorated_function
    rv = f(*args, **kwargs)
  File "/app/opac/webapp/main/views.py", line 985, in article_detail
    article_url, [article.title]),
  File "/app/opac/webapp/utils/related_articles_urls.py", line 9, in related_links
    get_google_results_searched_by_article_titles(titles)[0],
  File "/app/opac/webapp/utils/related_articles_urls.py", line 24, in get_google_results_searched_by_article_titles
    return [current_app.config.get("OPAC_GOOGLE_LINK") + title for title in titles]
  File "/app/opac/webapp/utils/related_articles_urls.py", line 24, in <listcomp>
    return [current_app.config.get("OPAC_GOOGLE_LINK") + title for title in titles]
TypeError: Can't convert 'NoneType' object to str implicitly
```

### Passos para reproduzir o problema
1. Acesse um artigo sem título. Ex: https://new.scielo.br/article/anp/1946.v4n2/179-180/
2. Será exibida a tela de Internal Error

### Comportamento esperado
Os artigos sem títulos também devem estar acessíveis. Ex. na versão anterior à alteração: https://www.scielosp.org/article/resp/2002.v76n6/769-770/es/

### Screenshots ou vídeos
N/A

### Anexos
N/A

### Ambiente utilizado
Erro ocorre em new.scielo.br e todos que estão atualizados com a versão da `master`

**Comment by patymori** [comment]
Validado no ambiente de homologação.
