### ISSUE TITLE
Erro ao gerar arquivo de migração rodando Docker

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#1439]
### Descrição do problema

Erro de permissão ao rodar o OPAC com Docker. 

### Passos para reproduzir o problema
1. docker-compose -f docker-compose-dev.yml build
2. docker-compose -f docker-compose-dev.yml up

Erro de permissão para gerar o arquivo: https://github.com/scieloorg/opac/blob/104c02a6b464b21e4ed11b8952e48d7b9e188cfc/opac/webapp/utils/page_migration.py#L17

https://github.com/scieloorg/opac/blob/104c02a6b464b21e4ed11b8952e48d7b9e188cfc/opac/webapp/utils/journal_static_page.py#L12

### Log de erro: 

```
opac_webapp_1  | PermissionError: [Errno 13] Permission denied: '/app/opac/journal_pages.log'
opac_webapp_1  | [2019-10-11 19:54:41 +0000] [9] [INFO] Worker exiting (pid: 9)
opac_webapp_1  | [2019-10-11 19:54:41 +0000] [29] [ERROR] Exception in worker process
opac_webapp_1  | Traceback (most recent call last):
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
opac_webapp_1  | 	worker.init_process()
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
opac_webapp_1  | 	self.load_wsgi()
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
opac_webapp_1  | 	self.wsgi = self.app.wsgi()
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
opac_webapp_1  | 	self.callable = self.load()
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
opac_webapp_1  | 	return self.load_wsgiapp()
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
opac_webapp_1  | 	return util.import_app(self.app_uri)
opac_webapp_1  |   File "/usr/local/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
opac_webapp_1  | 	__import__(module)
opac_webapp_1  |   File "/app/opac/manager.py", line 35, in <module>
opac_webapp_1  | 	from webapp.utils.journal_static_page import PAGE_NAMES_BY_LANG  # noqa
opac_webapp_1  |   File "/app/opac/webapp/utils/journal_static_page.py", line 12, in <module>
opac_webapp_1  | 	fh = logging.FileHandler('journal_pages.log', mode='w')
opac_webapp_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1014, in __init__
opac_webapp_1  | 	StreamHandler.__init__(self, self._open())
opac_webapp_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1043, in _open
opac_webapp_1  | 	return open(self.baseFilename, self.mode, encoding=self.encoding)
opac_webapp_1  | PermissionError: [Errno 13] Permission denied: '/app/opac/journal_pages.log'
opac_webapp_1  | [2019-10-11 19:54:41 +0000] [29] [INFO] Worker exiting (pid: 29)
opac_webapp_1  | [2019-10-11 19:54:42 +0000] [1] [INFO] Shutting down: Master
opac_webapp_1  | [2019-10-11 19:54:42 +0000] [1] [INFO] Reason: Worker failed to boot.
opac_webapp_1  | [2019-10-11 19:54:45 +0000] [1] [DEBUG] Current configuration:

```

**Comment by gustavofonseca** [comment]
Idealmente os logs devem ser impressos no `stderr` ao invés de serem escritos em arquivos.

**Comment by gustavofonseca** [comment]
Uma dúvida: o título fala em _gerar arquivo de migração rodando Docker_ mas na descrição exibe um comando para inicializar os serviços. As migrações de dados são executadas automaticamente ao subir a aplicação? Se sim, precisamos mudar isso urgentemente!
