### ISSUE TITLE
Erro ao acessar o site sem conteúdo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#369]
Ao acessar o site sem as métricas é retornado ao seguinte traceback: 

```python 
16/11/2016 10:26:14[2016-11-16 10:26:14 +0000] [6] [INFO] Starting gunicorn 19.6.0
16/11/2016 10:26:14[2016-11-16 10:26:14 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
16/11/2016 10:26:14[2016-11-16 10:26:14 +0000] [6] [INFO] Using worker: sync
16/11/2016 10:26:14[2016-11-16 10:26:14 +0000] [11] [INFO] Booting worker with pid: 11
16/11/2016 10:26:14[2016-11-16 10:26:14 +0000] [12] [INFO] Booting worker with pid: 12
16/11/2016 10:26:15[2016-11-16 10:26:15 +0000] [13] [INFO] Booting worker with pid: 13
16/11/2016 10:26:16 flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
16/11/2016 10:26:16  .format(x=modname), ExtDeprecationWarning
16/11/2016 10:26:16 flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
16/11/2016 10:26:16  .format(x=modname), ExtDeprecationWarning
16/11/2016 10:26:16 flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
16/11/2016 10:26:16  .format(x=modname), ExtDeprecationWarning
16/11/2016 10:29:11[2016-11-16 10:29:11 +0000] [13] [ERROR] Error handling request /
16/11/2016 10:29:11Traceback (most recent call last):
16/11/2016 10:29:11  File " gunicorn/workers/sync.py", line 135, in handle
16/11/2016 10:29:11    self.handle_request(listener, req, client, addr)
16/11/2016 10:29:11  File " gunicorn/workers/sync.py", line 176, in handle_request
16/11/2016 10:29:11    respiter = self.wsgi(environ, resp.start_response)
16/11/2016 10:29:11  File " flask/app.py", line 2000, in __call__
16/11/2016 10:29:11    return self.wsgi_app(environ, start_response)
16/11/2016 10:29:11  File " werkzeug/contrib/fixers.py", line 152, in __call__
16/11/2016 10:29:11    return self.app(environ, start_response)
16/11/2016 10:29:11  File " flask/app.py", line 1991, in wsgi_app
16/11/2016 10:29:11    response = self.make_response(self.handle_exception(e))
16/11/2016 10:29:11  File " flask/app.py", line 1567, in handle_exception
16/11/2016 10:29:11    reraise(exc_type, exc_value, tb)
16/11/2016 10:29:11  File " flask/app.py", line 1988, in wsgi_app
16/11/2016 10:29:11    response = self.full_dispatch_request()
16/11/2016 10:29:11  File " flask/app.py", line 1641, in full_dispatch_request
16/11/2016 10:29:11    rv = self.handle_user_exception(e)
16/11/2016 10:29:11  File " flask/app.py", line 1544, in handle_user_exception
16/11/2016 10:29:11    reraise(exc_type, exc_value, tb)
16/11/2016 10:29:11  File " flask/app.py", line 1639, in full_dispatch_request
16/11/2016 10:29:11    rv = self.dispatch_request()
16/11/2016 10:29:11  File " flask_debugtoolbar/__init__.py", line 125, in dispatch_request
16/11/2016 10:29:11    return view_func(**req.view_args)
16/11/2016 10:29:11  File "/app/opac/webapp/main/views.py", line 101, in index
16/11/2016 10:29:11    return render_template("collection/index.html", **context)
16/11/2016 10:29:11  File " flask/templating.py", line 134, in render_template
16/11/2016 10:29:11    context, ctx.app)
16/11/2016 10:29:11  File " flask/templating.py", line 116, in _render
16/11/2016 10:29:11    rv = template.render(context)
16/11/2016 10:29:11  File " jinja2/environment.py", line 989, in render
16/11/2016 10:29:11    return self.environment.handle_exception(exc_info, True)
16/11/2016 10:29:11  File " jinja2/environment.py", line 754, in handle_exception
16/11/2016 10:29:11    reraise(exc_type, exc_value, tb)
16/11/2016 10:29:11  File "index.html", line 1, in top-level template code
16/11/2016 10:29:11    {% extends "collection/base.html" %}
16/11/2016 10:29:11  File "base.html", line 1, in top-level template code
16/11/2016 10:29:11    {% extends "base.html" %}
16/11/2016 10:29:11  File "/app/opac/webapp/templates/base.html", line 46, in top-level template code
16/11/2016 10:29:11    {% block content %}{% endblock %}
16/11/2016 10:29:11  File "base.html", line 7, in block "content"
16/11/2016 10:29:11    {% block main_content %}{% endblock %}
16/11/2016 10:29:11  File "index.html", line 15, in block "main_content"
16/11/2016 10:29:11    {{ g.collection.metrics.total_journal }}
16/11/2016 10:29:11  File " jinja2/environment.py", line 408, in getattr
16/11/2016 10:29:11    return getattr(obj, attribute)
16/11/2016 10:29:11UndefinedError: 'dict object' has no attribute 'metrics'
```

**Comment by jamilatta** [comment]
Este erro já foi resolvido.
