### ISSUE TITLE
erro tentando enviar email com credenciais smtp inválidas

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#486]
### passos para reproduzir o erro:

- configurar credenciais inválidas
- criar um usuário admin via web
- salvar o novo usuário (para dispara o envio de email) 

### Stack Trace:

```
3/31/2017 6:58:14 PM[2017-03-31 18:58:14,690] ERROR in app: Exception on /admin/user/new/ [POST]
3/31/2017 6:58:14 PMTraceback (most recent call last):
3/31/2017 6:58:14 PM  File "/app/opac/webapp/utils.py", line 178, in send_email
3/31/2017 6:58:14 PM    webapp.mail.send(msg)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_mail.py", line 491, in send
3/31/2017 6:58:14 PM    with self.connect() as connection:
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_mail.py", line 144, in __enter__
3/31/2017 6:58:14 PM    self.host = self.configure_host()
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_mail.py", line 165, in configure_host
3/31/2017 6:58:14 PM    host.login(self.mail.username, self.mail.password)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/smtplib.py", line 729, in login
3/31/2017 6:58:14 PM    raise last_exception
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/smtplib.py", line 720, in login
3/31/2017 6:58:14 PM    initial_response_ok=initial_response_ok)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/smtplib.py", line 641, in auth
3/31/2017 6:58:14 PM    raise SMTPAuthenticationError(code, resp)
3/31/2017 6:58:14 PMsmtplib.SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')
3/31/2017 6:58:14 PMDuring handling of the above exception, another exception occurred:
3/31/2017 6:58:14 PMTraceback (most recent call last):
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
3/31/2017 6:58:14 PM    response = self.full_dispatch_request()
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
3/31/2017 6:58:14 PM    rv = self.handle_user_exception(e)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
3/31/2017 6:58:14 PM    reraise(exc_type, exc_value, tb)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
3/31/2017 6:58:14 PM    raise value
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
3/31/2017 6:58:14 PM    rv = self.dispatch_request()
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
3/31/2017 6:58:14 PM    return self.view_functions[rule.endpoint](**req.view_args)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_admin/base.py", line 69, in inner
3/31/2017 6:58:14 PM    return self._run_view(f, *args, **kwargs)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_admin/base.py", line 368, in _run_view
3/31/2017 6:58:14 PM    return fn(self, *args, **kwargs)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_admin/model/base.py", line 1997, in create_view
3/31/2017 6:58:14 PM    model = self.create_model(form)
3/31/2017 6:58:14 PM  File "/usr/local/lib/python3.5/site-packages/flask_admin/contrib/sqla/view.py", line 1085, in create_model
3/31/2017 6:58:14 PM    self.after_model_change(form, model, True)
3/31/2017 6:58:14 PM  File "/app/opac/webapp/admin/views.py", line 161, in after_model_change
3/31/2017 6:58:14 PM    was_sent, error_msg = model.send_confirmation_email()
3/31/2017 6:58:14 PM  File "/app/opac/webapp/models.py", line 55, in send_confirmation_email
3/31/2017 6:58:14 PM    return notifications.send_confirmation_email(self.email)
3/31/2017 6:58:14 PM  File "/app/opac/webapp/notifications.py", line 32, in send_confirmation_email
3/31/2017 6:58:14 PM    render_template('email/activate.html', confirm_url=confirm_url))
3/31/2017 6:58:14 PM  File "/app/opac/webapp/utils.py", line 181, in send_email
3/31/2017 6:58:14 PM    return (False, e.message)
3/31/2017 6:58:14 PMAttributeError: 'SMTPAuthenticationError' object has no attribute 'message'
```

**Comment by gustavofonseca** [comment]
Entendo que com a entrada de credenciais inválidas o sistema tenha mesmo que apresentar erro. Imagino que o ponto principal deste ticket é que o erro deve ser tratado de uma maneira diferente da que está sendo hoje. Como essa maneira desejada não está descrita, eu vou marcar o ticket com _wontfix_ e fechá-lo.
