### ISSUE TITLE
Erro 500 quando o ssm esta unreachable

### ISSUE THREAD

**Issue by jfunez** [scieloorg/opac#766]
#### Passos para reproduzir o erro:

1. Desligue o container do SSM
2. Acesse uma url que faça conexão com o SSM, por exemplo: `/media/assets/aiss/glogo.gif`
3. Pronto! Erro 500!

#### Stacktrace:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/opac/webapp/main/views.py", line 768, in media_assets_proxy
    return get_content_from_ssm(resource_ssm_path)
  File "/app/opac/webapp/main/views.py", line 756, in get_content_from_ssm
    ssm_response = requests.get(resource_ssm_full_url.strip())
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

#### Solução:

Tratar a exceção do requests e caso o recurso esteja indisponível retornar um 404..

**Comment by jfunez** [comment]
resolvido em: https://github.com/scieloorg/opac/pull/774/files#diff-994f42120a594778e32d2e59e4493b91R724
